version: "3.9"

services:

  dashboard:
    image: hugopp/cps-dashboard:latest
    ports:
      - "1880:1880"

  mosquitto:
    image: eclipse-mosquitto:2
    user: mosquitto
    volumes:
      - type: bind
        source: ./config/
        target: /mosquitto/config/
      - type: bind
        source: ./log/
        target: /mosquitto/log/
      - mosquitto-data:/mosquitto/data/
    ports:
      - "1883:1883" 
      - "9001:9001"

volumes:
  mosquitto-data:
  node-red-data:
